# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - diagram-of-class-jdr

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Build
        run: npm run build
      - name: Bundle artifact (with node_modules for fast start)
        run: |
         mkdir -p deploy
         cp -R .next package.json package-lock.json next.config.mjs deploy/
         cp -R public deploy/public || true
         cp -R node_modules deploy/node_modules
         echo "Artifact content:" && ls -1 deploy
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: .
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD84F72B1F024DED8134CD39CE83097E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1F888DA6FD449F7B5E51E46858DCC03 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_97644A5E996F4443944CCCC870D595A4 }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'diagram-of-class-jdr'
          slot-name: 'Production'
          package: .
          